# Generated by Django 4.0.1 on 2022-01-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компании')),
                ('manager_name', models.CharField(max_length=50, verbose_name='Имя директора')),
                ('manager_second_name', models.CharField(max_length=50, verbose_name='Фамилия директора')),
                ('manger_last_name', models.CharField(max_length=50, verbose_name='Отчество директора')),
                ('company_adress', models.CharField(max_length=100, verbose_name='Юредический адресс')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_account', models.CharField(max_length=100, verbose_name='Расчетный счет')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('product_unit_measure', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operation.paymentaccount', verbose_name='Расчетный счет')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Количество')),
                ('sold_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operation.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(to='operation.Company')),
                ('payment', models.ManyToManyField(to='operation.PaymentAccount')),
                ('product', models.ManyToManyField(to='operation.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ManyToManyField(blank=True, to='operation.Price')),
                ('product', models.ManyToManyField(blank=True, to='operation.Product')),
            ],
        ),
    ]
